language: common-lisp
os: linux

notifications:
  email: false

services:
  - docker

jobs:
  include:
    - name: update docs
      stage: deploy
      before_script:
        - docker pull quay.io/fisxoj/coo:master
        - git clone git@gitlab.com:/fisxoj/openapi
      script:
        - docker run --rm -it -v $PWD:/work:Z -v $PWD/openapi:/quicklisp/local-projects/openapi:Z quay.io/fisxoj/coo:master
      deploy:
        provider: pages:git
        edge: true
        local_dir: docs
      if: type = push AND branch = master
